# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 09c48047587566500a35caa8fd97df10c6d2856285bb2a905fb2fc25a4db0bba1398b764d2a66b06f1c8095008b53819b4f9c3f8ed18be8462586b2445a06f7e

test:
  secret_key_base: 7978e060762f4da038a35df4ccc101ed658f72ac755ee168c01129829adeafab92fa4c5e1e475596083e00597a91710f8b6ac6a4fbef131817d764b0f53fb8d8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
